

spring:
  application:
    name: teami
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/teamidb
    driver-class-name: org.mariadb.jdbc.Driver
    username: teami
    password: 1234

  jwt:
    secret: dlrjstlzmfltzldlsep1234
    expiration_time: 86400
server:
  port: 8999